/*
 * This source file was generated by the Gradle 'init' task
 */
package com.scratchgame;

import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.scratchgame.engine.GameEngine;
import com.scratchgame.model.Config;
import com.scratchgame.model.GameResult;
import com.scratchgame.utils.FileLoader;

import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.io.FileNotFoundException;

class AppTest {
    @Test
    public void testEvaluateMatrixWithBonusAndWin() throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        File file = FileLoader.loadFileFromResources("config.json");
        if (file == null) {
            throw new FileNotFoundException("File config.json not found in resources");
        }
        Config config = mapper.readValue(file, Config.class);
        GameEngine engine = new GameEngine(config);

        String[][] matrix = {
                { "C", "F", "F" },
                { "C", "F", "+1000" },
                { "F", "E", "B" }
        };

        GameResult result = engine.evaluateMatrix(matrix, 100);

        assertEquals(1750, result.reward());
        assertTrue(result.appliedWinCombinations().containsKey("F"));
        assertEquals("+1000", result.appliedBonusSymbol());
    }
}
