/*
 * This source file was generated by the Gradle 'init' task
 */
package com.scratchgame;

import org.junit.jupiter.api.Test;

import com.scratchgame.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
