/*
 * This source file was generated by the Gradle 'init' task
 */
package com.scratchgame;

import java.io.File;
import java.io.IOException;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.scratchgame.engine.GameEngine;
import com.scratchgame.model.Config;
import com.scratchgame.model.GameResult;

public class App {

    public static void main(String[] args) {
        String configPath = null;
        int bettingAmount = 0;

        for (int i = 0; i < args.length; i++) {
            if (args[i].equals("--config"))
                configPath = args[++i];
            else if (args[i].equals("--betting-amount"))
                bettingAmount = Integer.parseInt(args[++i]);
        }

        if (configPath == null || bettingAmount <= 0) {
            System.err.println("ERROR:: You have to provide config file path and betting amount");
            return;
        }

        ObjectMapper mapper = new ObjectMapper();
        Config config;
        try {
            config = mapper.readValue(new File(configPath), Config.class);
            GameEngine engine = new GameEngine(config);
            GameResult result = engine.play(bettingAmount);
            System.out.println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(result));
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
